### ISSUE TITLE
Dissolver causes crash

### ISSUE THREAD

**Issue by Pengu-Hunter** [al132mc/alchemistry#278] opened 2022-12-03 13:33 UTC
1.19.2
43.1.58
Alchemistry 2.2.3
AlchemyLib 1.0.18
ChemLib 2.0.14
[crash-2022-12-03_23.30.28-server.txt](https://github.com/SmashingMods/Alchemistry/files/10146462/crash-2022-12-03_23.30.28-server.txt)
Right clicking Dissolver instantly causes the game to crash.

**Comment by Dark-Arcana** [comment] 2022-12-03 19:41
Duplicate of https://github.com/SmashingMods/Alchemistry/issues/279

**Closed as completed by Dark-Arcana** 2022-12-03 19:41 UTC
