### ISSUE TITLE
Infinite Diamonds latest version

### ISSUE THREAD

**Issue by BideoGemu** [al132mc/alchemistry#249] opened 2022-09-22 13:34 UTC
Related to issue #232 , on latest version this bug is still present. It is replicable in the same way.

Do not hesitate if you need additional information, I'm not on my gaming computer, I can't take screen  for now.

**Comment by Dark-Arcana** [comment] 2022-09-22 19:24
The issue is fixed in my development environment but has not been pushed to a build on CurseForge yet. I've been unable to actually focus on development for a few weeks now due to work obligations. But I promise I'll get it pushed out as soon as I can.

**Comment by BideoGemu** [comment] 2022-09-25 14:47
No problem, thanks for taking the time to reply.

**Comment by DestinedByte** [comment] 2022-10-03 16:53
happening to me as well.
issue: Putting graphite into the combiner without selecting a recipe outputs infinite diamonds.
Repeatable: yes
Version: alchemistry-1.18.2-2.0.9

**Comment by Dark-Arcana** [comment] 2022-10-27 00:26
This was fixed a few versions ago. I forgot to close it. Please make a new issue to track related issues if you find it again!

**Closed as completed by Dark-Arcana** 2022-10-27 00:26 UTC
