### ISSUE TITLE
Alchemistry machines randomly stops working

### ISSUE THREAD

**Issue by GordonHollow** [al132mc/alchemistry#323] opened 2023-09-02 09:00 UTC
Playing ATM9, and sometimes machine from alchemistry just stop working until i open GUI of it
After opening it - i can see processing starts again from 0

All machines in loaded chunks and i also have my player near it, so even without chunkload they all loaded

**Comment by olivia-mativi** [comment] 2023-09-24 01:34
Also having this issue, most notably with fusion reactors. The materials sit inside the machine and don't actually process until I open the GUI. Chunks are loaded.

**Comment by dhebert-pro** [comment] 2024-01-08 12:03
Same for me with fusion reactor. Fusion Reactor is in a single chunk and the zone is chunkloaded. Already have the problem when I open the GUI though.
It stops working even if I am present. What is the problem ?

**Comment by cyb0124** [comment] 2024-01-14 18:33
Also sometimes happens with combiner when one set of input finishes processing and another set of input (for a different recipe) gets put in.

**Comment by cyb0124** [comment] 2024-01-14 19:46
`/setblock -34 78 -93 alchemistry:combiner[facing=north]{ForgeCaps:{},energy:100000,input:{Items:[{Count:4b,Slot:0,id:"chemlib:calcium"},{Count:4b,Slot:1,id:"chemlib:carbonate"}],Size:4},locked:0b,output:{Items:[],Size:1},paused:0b,progress:1,recipeId:"alchemistry:combiner/calcium_carbonate",searchText:"",sides:16383s}`
Here is the block data when it happens. Progress stuck at 1.

**Comment by cyb0124** [comment] 2024-01-14 21:16
I found the cause: the recipe is copied in `updateRecipe` but `equals` is not implemented for `AbstractProcessingRecipe`, causing the tile to constantly think that the recipe has changed, resetting the progress back to 0. The recipe set by GUI is not copied so that's why opening the GUI fixes it.

I have opened SmashingMods/AlchemyLib#7 which fixes this issue.

**Comment by Dark-Arcana** [comment] 2024-01-16 20:59
I merged this PR. I'm going to close this issue. If the issue happens again *after* updating AlchemyLib on your end, re-open it with details.

**Closed as completed by Dark-Arcana** 2024-01-16 20:59 UTC
